version: 2
jobs:
  install:
    docker:
    - image: circleci/golang:1.10
    working_directory: /go/src/github.com/nomkhonwaan/myblog-server
    steps:
    - checkout
    - run: make install
    - save_cache:
        paths:
        - vendor
        key: v1-dependencies-{{ checksum "Gopkg.toml" }}
  build:
    machine: true
    working_directory: /go/src/github.com/nomkhonwaan/myblog-server
    steps:
    - setup_remote_docker:
        docker_layer_caching: true
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "Gopkg.toml" }}
    - run: make build-docker
  test:
    docker:
    - image: circleci/golang:1.10
    working_directory: /go/src/github.com/nomkhonwaan/myblog-server
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "Gopkg.toml" }}
    - run: make test
  publish_to_registry:
    machine: true
    steps:
    - setup_remote_docker
    - run: |
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - run: make publish-to-registry
workflows:
  version: 2
  build_test_and_deploy:
    jobs:
    - install
    - test:
        requires:
        - install
    - build:
        requires:
        - test
    - publish_to_registry:
        requires:
        - build