version: 2
jobs:
  install:
    docker:
    - image: circleci/golang:1.10
    working_directory: /go/src/github.com/nomkhonwaan/myblog-server
    steps:
    - checkout
    - run: make install
    - save_cache:
        paths:
        - vendor
        key: v1-dependencies-{{ checksum "Gopkg.toml" }}
  test:
    docker:
    - image: circleci/golang:1.10
    working_directory: /go/src/github.com/nomkhonwaan/myblog-server
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "Gopkg.toml" }}
    - run: make test
  build_and_publish_to_registry:
    machine: true
    working_directory: ~/repo
    steps:
    - checkout
    - run: make build-docker
    - run: |
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - run: make publish-to-registry
workflows:
  version: 2
  build_test_and_deploy:
    jobs:
    - install
    - test:
        requires:
        - install
    - build_and_publish_to_registry:
        requires:
        - test